id: I9562B9F7
legacy_id: P003034
ocr_import_info:
  bdrc_scan_id: W23900
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T10:27:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:01:40.412794+00:00'
last_modified: 2022-09-02 13:02:05.693823
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23900
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23900
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་ཆོས་འབྱུང་སྐོར། ༼འབའ་ཉག་དཔེ་མཛོད་ཁང༽
  author: པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6847002711282326
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I3198:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3198
      total_pages: 402
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3198.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6847002711282326
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
