id: P003034
initial_creation_type: ocr
source_metadata:
  id: bdr:W23900
  title: བཀའ་གདམས་ཆོས་འབྱུང་སྐོར། ༼འབའ་ཉག་དཔེ་མཛོད་ཁང༽
  author: ''
  volumes:
    99ed4957be2340088e5ac9793c0f72d5:
      image_group_id: I3198
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
