id: P003034
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:35:44.167638
source_metadata:
  id: bdr:W23900
  title: བཀའ་གདམས་ཆོས་འབྱུང་སྐོར། ༼འབའ་ཉག་དཔེ་མཛོད་ཁང༽
  author: ''
  volumes:
    99ed4957be2340088e5ac9793c0f72d5:
      image_group_id: I3198
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
